package com.kauanferreira.smartorder.entity;

import jakarta.persistence.*;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

/**
 * Entity representing a delivery address in the SmartOrder system.
 *
 * <p>Each address belongs to a {@link User} and can be used
 * as a shipping destination for orders.</p>
 *
 * @author Kauan
 * @version 1.0
 * @since 2026
 */
@Entity
@Table(name = "tb_address")
@Getter
@Setter
@AllArgsConstructor
@NoArgsConstructor
public class Address {

    /**
     * Unique identifier for the address.
     * Auto-generated by the database using BIGSERIAL.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Street name of the address.
     */
    @NotBlank(message = "Street is required")
    @Size(max = 200, message = "Street must not exceed 200 characters")
    @Column(nullable = false, name = "street", length = 200)
    private String street;

    /**
     * House or building number. Supports values like "123", "S/N", "123-A".
     */
    @NotBlank(message = "Number is required")
    @Size(max = 20, message = "Number must not exceed 20 characters")
    @Column(nullable = false, name = "number", length = 20)
    private String number;

    /**
     * Optional complement such as apartment, block, or floor.
     */
    @Size(max = 100, message = "Complement must not exceed 100 characters")
    @Column(length = 100, name = "complement")
    private String complement;

    /**
     * City where the address is located.
     */
    @NotBlank(message = "City is required")
    @Size(max = 100, message = "City must not exceed 100 characters")
    @Column(nullable = false, name = "city", length = 100)
    private String city;

    /**
     * State or province where the address is located.
     */
    @NotBlank(message = "State is required")
    @Size(max = 50, message = "State must not exceed 50 characters")
    @Column(nullable = false, name = "state", length = 50)
    private String state;

    /**
     * Postal or zip code for the address.
     */
    @NotBlank(message = "Zip code is required")
    @Size(max = 20, message = "Zip code must not exceed 20 characters")
    @Column(nullable = false, name = "zip_code", length = 20)
    private String zipCode;

    /**
     * Country where the address is located.
     * Defaults to "Brasil" in the database.
     */
    @NotBlank(message = "Country is required")
    @Size(max = 50, message = "Country must not exceed 50 characters")
    @Column(nullable = false, name = "country", length = 50)
    private String country;

    /**
     * User who owns this address.
     * Loaded lazily to optimize performance.
     */
    @NotNull(message = "User is required")
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "user_id", nullable = false)
    private User user;
}
