package com.kauanferreira.smartorder.entity;

import jakarta.persistence.*;
import jakarta.validation.constraints.Min;
import jakarta.validation.constraints.NotNull;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import org.hibernate.annotations.CreationTimestamp;

import java.time.LocalDateTime;

/**
 * Entity representing an item in a user's shopping cart.
 *
 * <p>Each cart item links a {@link User} to a {@link Product} with a specified
 * quantity. A unique constraint on (user_id, product_id) ensures the same
 * product cannot appear twice in a user's cart.</p>
 *
 * @author Kauan Santos Ferreira
 * @version 1.0
 * @since 2026
 * @see User
 * @see Product
 */
@Entity
@Table(name = "tb_cart_item")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
public class CartItem {

    /**
     * Unique identifier for the cart item.
     * Auto-generated by the database using BIGSERIAL.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * The user who owns this cart item.
     * Loaded lazily to optimize performance.
     */
    @NotNull(message = "User is required")
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "user_id", nullable = false)
    private User user;

    /**
     * The product added to the cart.
     * Loaded lazily to optimize performance.
     */
    @NotNull(message = "Product is required")
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "product_id", nullable = false)
    private Product product;

    /**
     * Quantity of the product in the cart.
     * Must be at least 1.
     */
    @NotNull
    @Min(value = 1, message = "Quantity must be at least 1")
    @Column(nullable = false, name = "quantity", columnDefinition = "INT")
    private Integer quantity;

    /**
     * Timestamp of when the item was added to the cart.
     * Automatically set on entity creation and cannot be updated.
     */
    @CreationTimestamp
    @Column(name = "added_at", nullable = false, updatable = false)
    private LocalDateTime addedAt;
}
