package com.kauanferreira.smartorder.entity;

import jakarta.persistence.*;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Size;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

/**
 * Entity representing a product category in the SmartOrder system.
 *
 * <p>Categories are used to group and organize products,
 * enabling better navigation and filtering for customers.</p>
 *
 * @author Kauan
 * @version 1.0
 * @since 2026
 */

@Entity
@Table(name = "tb_category")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
public class Category {

    /**
     * Unique identifier for the category.
     * Auto-generated by the database using BIGSERIAL.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Name of the category.
     * Must not be blank and has a maximum length of 100 characters.
     */
    @NotBlank(message = "Category name must not be blank")
    @Size(max = 100, message = "Category name must not exceed 100 characters")
    @Column(unique = true, name = "name", nullable = false, length = 100)
    private  String name;

    /**
     * Optional description of the category.
     */
    @Column(name = "description", columnDefinition = "TEXT")
    private String description;
}
