package com.kauanferreira.smartorder.entity;

import jakarta.persistence.*;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import org.hibernate.annotations.CreationTimestamp;

import java.time.LocalDateTime;

@Entity
@Table(name = "tb_chat_message")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
public class ChatMessage {

    /**
     * Unique identifier for the chat message.
     * Auto-generated by the database using BIGSERIAL.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * The user who sent the message.
     * Loaded lazily to optimize performance.
     */
    @NotNull(message = "Sender is required")
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "sender_id", nullable = false)
    private User sender;

    /**
     * The user who receives the message.
     * Loaded lazily to optimize performance.
     */
    @NotNull(message = "Receiver is required")
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "receiver_id", nullable = false)
    private User receiver;

    /**
     * The product this conversation is about.
     * Every chat message must be linked to a product for context.
     * Loaded lazily to optimize performance.
     */
    @NotNull(message = "Product is required")
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "product_id", nullable = false)
    private Product product;

    /**
     * The text content of the message.
     */
    @NotBlank(message = "Message content is required")
    @Column(name = "message", nullable = false, columnDefinition = "TEXT")
    private String message;

    /**
     * Timestamp of when the message was sent.
     * Automatically set on entity creation and cannot be updated.
     */
    @CreationTimestamp
    @Column(name = "sent_at", nullable = false, updatable = false)
    private LocalDateTime sentAt;

    /**
     * Indicates whether the receiver has read the message.
     * Defaults to false in the database.
     */
    @NotNull
    @Column(name = "is_read", nullable = false, columnDefinition = "BOOLEAN")
    private Boolean isRead = false;
}
