package com.kauanferreira.smartorder.entity;

import jakarta.persistence.*;
import jakarta.validation.constraints.NotNull;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import org.hibernate.annotations.CreationTimestamp;

import java.time.LocalDateTime;

/**
 * Entity representing a favorited product in a user's wishlist.
 *
 * <p>Links a {@link User} to a {@link Product} they have favorited.
 * A unique constraint on (user_id, product_id) ensures the same
 * product cannot be favorited twice by the same user.</p>
 *
 * @author Kauan Santos Ferreira
 * @version 1.0
 * @since 2026
 * @see User
 * @see Product
 */
@Entity
@Table(name = "tb_favorite")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
public class Favorite {

    /**
     * Unique identifier for the favorite.
     * Auto-generated by the database using BIGSERIAL.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * The user who favorited the product.
     * Loaded lazily to optimize performance.
     */
    @NotNull(message = "User is required")
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "user_id", nullable = false)
    private User user;

    /**
     * The product that was favorited.
     * Loaded lazily to optimize performance.
     */
    @NotNull(message = "Product is required")
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "product_id", nullable = false)
    private Product product;

    /**
     * Timestamp of when the product was favorited.
     * Automatically set on entity creation and cannot be updated.
     */
    @CreationTimestamp
    @Column(name = "added_at", nullable = false, updatable = false)
    private LocalDateTime addedAt;
}
