package com.kauanferreira.smartorder.entity;

import jakarta.persistence.*;
import jakarta.validation.constraints.Min;
import jakarta.validation.constraints.NotNull;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.math.BigDecimal;

/**
 * Entity representing a single item within an {@link Order}.
 *
 * <p>Each order item references a {@link Product} and stores
 * the quantity, unit price at the time of purchase, and
 * the calculated subtotal.</p>
 *
 * @author Kauan
 * @version 1.0
 * @since 2026
 */
@Entity
@Table(name = "tb_order_item")
@Getter
@Setter
@AllArgsConstructor
@NoArgsConstructor
public class OrderItem {

    /**
     * Unique identifier for the order item.
     * Auto-generated by the database using BIGSERIAL.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Quantity of the product in this order item.
     * Must be at least 1.
     */
    @NotNull(message = "Quantity is required")
    @Min(value = 1, message = "Quantity must be at least 1")
    @Column(name = "quantity", nullable = false)
    private Integer quantity;

    /**
     * Unit price of the product at the time of purchase.
     * Preserved to maintain order history even if product price changes.
     */
    @NotNull(message = "Price is required")
    @Column(name = "price", nullable = false, precision = 10, scale = 2)
    private BigDecimal price;

    /**
     * Calculated subtotal for this item (quantity * price).
     */
    @NotNull(message = "Subtotal is required")
    @Column(name = "subtotal", nullable = false, precision = 12, scale = 2)
    private BigDecimal subtotal;

    /**
     * Order to which this item belongs.
     * Loaded lazily to optimize performance.
     */
    @NotNull(message = "Order is required")
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "order_id", nullable = false)
    private Order order;

    /**
     * Product referenced by this order item.
     * Loaded lazily to optimize performance.
     */
    @NotNull(message = "Product is required")
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "product_id", nullable = false)
    private Product product;
}
