package com.kauanferreira.smartorder.entity;

import jakarta.persistence.*;
import jakarta.validation.constraints.*;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.math.BigDecimal;
import java.time.LocalDateTime;

/**
 * Entity representing a product in the SmartOrder system.
 *
 * <p>Products belong to a {@link Category} and contain information
 * about pricing, stock availability, and active status for
 * e-commerce catalog management.</p>
 *
 * @author Kauan Santos Ferreira
 * @version 1.0
 * @since 2026
 */
@Entity
@Table(name = "tb_product")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
public class Product {

    /**
     * Unique identifier for the product.
     * Auto-generated by the database using BIGSERIAL.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Name of the product.
     * Must not be blank and has a maximum length of 150 characters.
     */
    @NotBlank(message = "Product name is required")
    @Size(max = 150, message = "Product name must not exceed 150 characters")
    @Column(nullable = false, length = 150, name = "name")
    private String name;

    /**
     * Optional detailed description of the product.
     */
    @Column(name = "description", columnDefinition = "TEXT")
    private String description;

    /**
     * Unit price of the product.
     * Must be zero or positive.
     */
    @NotNull(message = "Product price is required")
    @Min(value = 0, message = "Product price must be zero or positive")
    @Column(nullable = false, name = "price", precision = 10, scale = 2)
    private BigDecimal price;

    /**
     * Available stock quantity.
     * Must be zero or positive. Defaults to 0 in the database.
     */
    @NotNull(message = "Stock quantity is required")
    @Min(value = 0, message = "Stock quantity must be zero or positive")
    @Column(nullable = false, name = "stock_quantity", columnDefinition = "INT")
    private Integer stockQuantity;

    /**
     * Optional URL pointing to the product image.
     */
    @Size(max = 500, message = "Image URL must not exceed 500 characters")
    @Column(name = "image_url", length = 500)
    private String imageUrl;

    /**
     * Indicates whether the product is active and visible in the catalog.
     * Defaults to true in the database.
     */
    @NotNull(message = "Active status is required")
    @Column(nullable = false, name = "active", columnDefinition = "BOOLEAN")
    private Boolean active;

    /**
     * Discount percentage applied to the product's original price.
     * Nullable — if null or zero, the product has no active promotion.
     * The final price is calculated as: price - (price * discountPercent / 100).
     */
    @Min(value = 0, message = "Discount percent must be zero or positive")
    @Max(value = 100, message = "Discount percent must not exceed 100")
    @Column(name = "discount_percent")
    private Integer discountPercent;

    /**
     * Original stock quantity when the product was first listed or restocked.
     * Used to calculate the "sold percentage" for deal progress bars:
     * soldPercent = ((initialStock - stockQuantity) / initialStock) * 100.
     */
    @Min(value = 0, message = "Initial stock must be zero or positive")
    @Column(name = "initial_stock", columnDefinition = "INT")
    private Integer initialStock;

    /**
     * Expiration date and time for the product's deal/promotion.
     * Nullable — if null, the discount has no expiration.
     * Used for countdown timers in the store's "Today's Deals" section.
     */
    @Column(name = "deal_expires_at")
    private LocalDateTime dealExpiresAt;

    /**
     * Indicates whether the product is featured in highlighted sections
     * such as the hero carousel or "Picked for you" grid.
     * Defaults to false in the database.
     */
    @Column(name = "featured", columnDefinition = "BOOLEAN")
    private Boolean featured;

    /**
     * Category to which the product belongs.
     * Loaded lazily to optimize performance.
     */
    @NotNull(message = "Product category is required")
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "category_id", nullable = false)
    private Category category;
}
