package com.kauanferreira.smartorder.entity;

import jakarta.persistence.*;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import org.hibernate.annotations.CreationTimestamp;

import java.time.LocalDateTime;

/**
 * Entity representing a pre-defined quick reply message for chat.
 *
 * <p>Allows vendors/admins to create reusable response templates
 * for frequently asked questions in customer chat conversations.
 * Each quick reply belongs to a specific {@link User} (vendor).</p>
 *
 * @author Kauan Santos Ferreira
 * @version 1.0
 * @since 2026
 * @see User
 */
@Entity
@Table(name = "tb_quick_reply")
@Getter
@Setter
@AllArgsConstructor
@NoArgsConstructor
public class QuickReply {

    /**
     * Unique identifier for the quick reply.
     * Auto-generated by the database using BIGSERIAL.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * The vendor/admin who created this quick reply.
     * Loaded lazily to optimize performance.
     */
    @NotNull(message = "Quick reply user is required")
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "user_id", nullable = false)
    private User user;

    /**
     * Short title to identify the quick reply (e.g., "Greeting", "Delivery info").
     */
    @NotBlank(message = "Quick reply title is required")
    @Column(name = "title",length = 100, nullable = false)
    private String title;

    /**
     * Full message content of the quick reply.
     */
    @NotBlank(message = "Quick reply message is required")
    @Column(name = "message", columnDefinition = "TEXT")
    private String message;

    /**
     * Timestamp of when the quick reply was created.
     * Automatically set on entity creation and cannot be updated.
     */
    @CreationTimestamp
    @Column(name = "created_at", nullable = false, updatable = false)
    private LocalDateTime createdAt;
}
