package com.kauanferreira.smartorder.entity;

import jakarta.persistence.*;
import jakarta.validation.constraints.Max;
import jakarta.validation.constraints.Min;
import jakarta.validation.constraints.NotNull;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import org.hibernate.annotations.CreationTimestamp;

import java.time.LocalDateTime;

/**
 * Entity representing a product review in the SmartOrder system.
 *
 * <p>Each review links a {@link User} to a {@link Product} with a star rating
 * and an optional comment. A unique constraint on (user_id, product_id)
 * ensures each user can only review a product once.</p>
 *
 * @author Kauan Santos Ferreira
 * @version 1.0
 * @since 2026
 * @see User
 * @see Product
 */
@Entity
@Table(name = "tb_review")
@Getter
@Setter
@AllArgsConstructor
@NoArgsConstructor
public class Review {

    /**
     * Unique identifier for the review.
     * Auto-generated by the database using BIGSERIAL.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * The user who wrote the review.
     * Loaded lazily to optimize performance.
     */
    @NotNull(message = "Review user is required")
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "user_id", nullable = false)
    private User user;

    /**
     * The product being reviewed.
     * Loaded lazily to optimize performance.
     */
    @NotNull(message = "Review product is required")
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "product_id", nullable = false)
    private Product product;

    /**
     * Star rating for the product, from 1 (worst) to 5 (best).
     */
    @NotNull(message = "Rating is required")
    @Min(value = 1, message = "Rating must be at least 1")
    @Max(value = 5, message = "Rating must be at most 5")
    @Column(name = "rating", nullable = false, columnDefinition = "INT")
    private Integer rating;

    @Column(name = "comment", columnDefinition = "TEXT")
    private String comment;

    /**
     * Timestamp of when the review was created.
     * Automatically set on entity creation and cannot be updated.
     */
    @CreationTimestamp
    @Column(name = "created_at", nullable = false, updatable = false)
    private LocalDateTime createdAt;
}
