package com.kauanferreira.smartorder.entity;

import jakarta.persistence.*;
import jakarta.validation.constraints.NotNull;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import org.hibernate.annotations.CreationTimestamp;

import java.time.LocalDateTime;

/**
 * Entity representing a like on a product review.
 *
 * <p>Links a {@link User} to a {@link Review} they have liked.
 * A unique constraint on (user_id, review_id) ensures the same
 * user cannot like a review more than once.</p>
 *
 * @author Kauan Santos Ferreira
 * @version 1.0
 * @since 2026
 * @see User
 * @see Review
 */
@Entity
@Table(name = "tb_review_like")
@Getter
@Setter
@AllArgsConstructor
@NoArgsConstructor
public class ReviewLike {

    /**
     * Unique identifier for the review like.
     * Auto-generated by the database using BIGSERIAL.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * The user who liked the review.
     * Loaded lazily to optimize performance.
     */
    @NotNull(message = "User is required")
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "user_id", nullable = false)
    private User user;

    /**
     * The review that was liked.
     * Loaded lazily to optimize performance.
     */
    @NotNull(message = "Review is required")
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "review_id", nullable = false)
    private Review review;

    /**
     * Timestamp of when the review was liked.
     * Automatically set on entity creation and cannot be updated.
     */
    @CreationTimestamp
    @Column(name = "created_at", nullable = false, updatable = false)
    private LocalDateTime createdAt;
}
