package com.kauanferreira.smartorder.entity;

import com.kauanferreira.smartorder.enums.Role;
import jakarta.persistence.*;
import jakarta.validation.constraints.Email;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Size;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import org.hibernate.annotations.CreationTimestamp;

import java.time.LocalDateTime;

/**
 * Entity representing a user in the SmartOrder system.
 *
 * <p>Users can have roles of ADMIN or CUSTOMER, which determine
 * their access level and permissions within the application.</p>
 *
 * @author Kauan
 * @version 1.0
 * @since 2026
 */
@Entity
@Table(name = "tb_user")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
public class User {

    /**
     * Unique identifier for the user.
     * Auto-generated by the database using BIGSERIAL.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Full name of the user.
     */
    @NotBlank(message = "Name is required")
    @Size(max = 100, message = "Name must not exceed 100 characters")
    @Column(nullable = false, length = 100, name = "name")
    private String name;

    /**
     * Email address of the user. Must be unique across the system.
     * Used for authentication and communication.
     */
    @Email
    @NotBlank(message = "Email is required")
    @Size(max = 150, message = "Email must not exceed 150 characters")
    @Column(nullable = false, length = 150, unique = true, name = "email")
    private String email;

    /**
     * Encrypted password for authentication.
     * Stored as a BCrypt hash.
     */
    @NotBlank(message = "Password is required")
    @Size(max = 255, message = "Password must not exceed 255 characters")
    @Column(nullable = false, length = 255, name = "password")
    private String password;

    /**
     * Role of the user determining access level.
     * Stored as a string value (ADMIN or CUSTOMER).
     */
    @Enumerated(EnumType.STRING)
    @Column(nullable = false, length = 20, name = "role")
    private Role role;

    /**
     * Optional phone number for contact purposes.
     */
    @Size(max = 20, message = "Phone number must not exceed 20 characters")
    @Column(length = 20, name = "phone")
    private String phone;

    /**
     * Timestamp of when the user account was created.
     * Automatically set on entity creation and cannot be updated.
     */
    @CreationTimestamp
    @Column(name = "created_at", updatable = false, nullable = false)
    private LocalDateTime createdAt;
}
